// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDinyRdoGDkDbORt3ZroUq1hcw-TNIvHkw',
    appId: '1:62370760292:web:f230224f00b9b176d80171',
    messagingSenderId: '62370760292',
    projectId: 'gcjm-collection-app',
    authDomain: 'gcjm-collection-app.firebaseapp.com',
    storageBucket: 'gcjm-collection-app.firebasestorage.app',
    measurementId: 'G-KF4ZB97Z5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bB9TjgBzpZ06oTOU72RLaS_02N2mT7Y',
    appId: '1:62370760292:android:9b11f99f8dc590e0d80171',
    messagingSenderId: '62370760292',
    projectId: 'gcjm-collection-app',
    storageBucket: 'gcjm-collection-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnE6tLKY4TlGPq6mt0t3pv64oMFzzQ2rA',
    appId: '1:62370760292:ios:adadc609bb313c84d80171',
    messagingSenderId: '62370760292',
    projectId: 'gcjm-collection-app',
    storageBucket: 'gcjm-collection-app.firebasestorage.app',
    iosBundleId: 'com.example.gcjmCollectionApp',
  );
}
