// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8cTgBPdKpNYTTF1rsFRwZiUeLhRCtD08',
    appId: '1:126000201399:web:b7fc9806c086d74f641732',
    messagingSenderId: '126000201399',
    projectId: 'gcjmcollectionapp',
    authDomain: 'gcjmcollectionapp.firebaseapp.com',
    storageBucket: 'gcjmcollectionapp.firebasestorage.app',
    measurementId: 'G-9EEHJ9Z0XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5flzgl-6LglgHvIz1hjGXbRoOusMd5is',
    appId: '1:126000201399:android:9974ad0df9d16c34641732',
    messagingSenderId: '126000201399',
    projectId: 'gcjmcollectionapp',
    storageBucket: 'gcjmcollectionapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLCZzXw0S-PPjxRH_LiIwgPWfSAQh-3E',
    appId: '1:126000201399:ios:ce9a4bf6715bb366641732',
    messagingSenderId: '126000201399',
    projectId: 'gcjmcollectionapp',
    storageBucket: 'gcjmcollectionapp.firebasestorage.app',
    iosBundleId: 'com.example.gcjmCollectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGLCZzXw0S-PPjxRH_LiIwgPWfSAQh-3E',
    appId: '1:126000201399:ios:ce9a4bf6715bb366641732',
    messagingSenderId: '126000201399',
    projectId: 'gcjmcollectionapp',
    storageBucket: 'gcjmcollectionapp.firebasestorage.app',
    iosBundleId: 'com.example.gcjmCollectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8cTgBPdKpNYTTF1rsFRwZiUeLhRCtD08',
    appId: '1:126000201399:web:f7bea8aaa4a4403c641732',
    messagingSenderId: '126000201399',
    projectId: 'gcjmcollectionapp',
    authDomain: 'gcjmcollectionapp.firebaseapp.com',
    storageBucket: 'gcjmcollectionapp.firebasestorage.app',
    measurementId: 'G-7SWMY0YZ8Z',
  );
}
